Repository celery/celery, pull requests merged in 2018-05, with the labels that each got.

#4703 Small change in celery.app.base.Celery. (Redundant code improved)
  celery/app/base.py
Labels: PR Type: Enhancement

#4696 result_backend setting supports rediss:// protocol URLs
  celery/app/backends.py
  celery/backends/redis.py
  docs/userguide/configuration.rst
  t/unit/backends/test_redis.py
Labels: Component: Redis Results Backend, PR Type: Enhancement

#4690 Pass parameters to the first task in chain().apply_async(params) (#4643)
  celery/canvas.py
  t/unit/tasks/test_canvas.py
Labels: Component: Canvas, PR Type: Bugfix

#4709 Do not subscribe to Redis channels when results are ignored
  celery/app/base.py
  celery/app/task.py
  celery/backends/redis.py
  celery/result.py
  t/integration/conftest.py
  t/integration/tasks.py
  t/integration/test_canvas.py
  t/integration/test_tasks.py
  t/unit/backends/test_redis.py
  t/unit/tasks/test_result.py
  t/unit/tasks/test_tasks.py
Labels: Component: Redis Results Backend, PR Type: Bugfix

#4725 Extract creation of lookup key into a helper
  celery/utils/dispatch/signal.py
Labels: Component: Signals, PR Type: Enhancement

#4719 Maybe fix #4699
  celery/utils/dispatch/signal.py
  t/unit/utils/test_dispatcher.py
Labels: Component: Signals, PR Type: Bugfix

#4723 Bump linters to Python 3.6
  .travis.yml
  tox.ini
Labels: Category: Tests, PR Type: Enhancement

#4724 Changed documentation on eventlet
  docs/userguide/concurrency/eventlet.rst
Labels: PR Type: Enhancement

#4745 Document ignore_result task execution option
  Changelog
  docs/userguide/calling.rst
  docs/userguide/tasks.rst
Labels: Issue Type: Documentation

#4762 Fixes issue #4731
  CONTRIBUTORS.txt
  celery/bin/celery.py
  t/unit/bin/test_report.py
Labels: Component: Django, PR Type: Bugfix

#4776 remove jython support
  requirements/jython.txt
  setup.py
Labels: Status: In Progress
