Repository celery/celery, pull requests merged in 2018-07, with the labels that each got.

#4880 Fix crontab documentation
  celery/schedules.py
  docs/userguide/periodic-tasks.rst
Labels: Status: Ready For Merge ✔

#4456 Perform a serialization roundtrip on eager apply_async.
  celery/app/task.py
  t/unit/app/test_builtins.py
  t/unit/tasks/test_tasks.py
Labels: PR Type: Enhancement, Status: Ready For Merge ✔

#4864 JSON Serialization fails when exception arguments are not JSON-serializable Fixes #4860
  CONTRIBUTORS.txt
  celery/backends/base.py
  celery/utils/serialization.py
  t/unit/backends/test_base.py
  t/unit/utils/test_serialization.py
Labels: PR Type: Bugfix

#4751 Enable automatic result expiration with couchbase backend
  celery/backends/couchbase.py
  docs/userguide/configuration.rst
  t/unit/backends/test_couchbase.py
Labels: Component: Couchbase Results Backend, Issue Type: Enhancement

#4852 Python 3.7 compat issues
  celery/backends/asynchronous.py
  celery/backends/redis.py
  celery/backends/rpc.py
  docs/internals/reference/celery.backends.asynchronous.rst
  t/unit/backends/test_redis.py
Labels: PR Type: Enhancement, Python Version: Python 3

#4902 Added compatibility with python 3.7
  celery/app/routes.py
  t/unit/app/test_routes.py
Labels: Python Version: Python 3

#4897 Add autoscaler information on stats inspect command
  celery/worker/autoscale.py
  t/unit/worker/test_autoscale.py
Labels: Component: Autoscaling, PR Type: Bugfix, Priority: Low, Status: In Progress

#4909 Increased test coverage for celery.worker.Request
  t/unit/worker/test_request.py
Labels: PR Type: Enhancement

#4908 Fix error when timelimit header contains a None value
  celery/worker/request.py
  t/unit/worker/test_request.py
Labels: PR Type: Bugfix

#4911 pypy version update
  .travis.yml
Labels: PR Type: Enhancement
