Repository celery/celery, pull requests merged in 2018-11, with the labels that each got.

#5167 Fix typo.
  celery/contrib/rdb.py
Labels: Category: Documentation, PR Type: Bugfix

#5124 Fix test by using utcfromtimestamp instead of fromtimestamp
  t/unit/app/test_beat.py
Labels: Category: Tests, Component: Celerybeat, PR Type: Enhancement

#5168 Fix import deprecation warning on Python 3.7
  celery/canvas.py
Labels: PR Type: Enhancement, Python Version: Python 3

#5134 Documentation - add example systemd celerybeat.service file
  docs/userguide/daemonizing.rst
  extra/systemd/celery.conf
  extra/systemd/celerybeat.service
Labels: Category: Documentation

#5185 Add CosmosDB storage backend
  README.rst
  celery/app/backends.py
  celery/app/defaults.py
  celery/backends/cosmosdbsql.py
  docs/internals/reference/celery.backends.cosmosdbsql.rst
  docs/userguide/configuration.rst
  requirements/extras/cosmosdbsql.txt
  requirements/test-ci-default.txt
  setup.py
  t/unit/backends/test_cosmosdbsql.py
Labels: Category: Results Backend, PR Type: Feature

#5205 fix: wrong configuration name CELERY_ACKS_LATE
  docs/userguide/configuration.rst
Labels: Category: Documentation
