Repository celery/celery, pull requests merged in 2018-03, with the labels that each got.

#4572 fixes shadow_name issue when using old Task
  celery/app/task.py
  t/unit/tasks/test_tasks.py
Labels: PR Type: Bugfix

#4595 Changelog for 4.2.0
  Changelog
  docs/history/changelog-4.1.rst
  docs/history/index.rst
Labels: Category: Packaging and Release Management

#4482 Add docker-compose and base dockerfile for development
  CONTRIBUTING.rst
  CONTRIBUTORS.txt
  celery/contrib/testing/worker.py
  docker/.env
  docker/Dockerfile
  docker/docker-compose.yml
  docker/entrypoint
  docker/scripts/create-linux-user.sh
  docker/scripts/install-couchbase.sh
  docker/scripts/install-pyenv.sh
  t/integration/conftest.py
  t/integration/tasks.py
  t/integration/test_canvas.py
  tox.ini
Labels: Category: Deployment, Category: Tests, Status: Ready For Merge ✔

#4602 Update Changelog after merging #4482
  Changelog
Labels: Category: Packaging and Release Management

#4617 Allow join in eager canvas application
  Changelog
  celery/canvas.py
  docs/whatsnew-4.2.rst
  t/integration/tasks.py
  t/integration/test_canvas.py
  t/unit/tasks/test_canvas.py
Labels: PR Type: Enhancement
