Repository celery/celery, pull requests merged in 2018-10, with the labels that each got.

#5018 Handle microseconds when scheduling
  celery/beat.py
  t/unit/app/test_beat.py
Labels: Component: Celerybeat, PR Type: Enhancement

#5097 fixed pytest 4 deprecation warning
  celery/beat.py
  celery/contrib/pytest.py
Labels: Category: Tests

#4997 Deadlock on inqueue close (#4185)
  celery/concurrency/asynpool.py
Labels: PR Type: Bugfix, Status: Needs Test Coverage ✘

#5114 fix: fix celery.Scheduler._when use utctimetuple replace timetuple
  celery/beat.py
  t/unit/app/test_beat.py
Labels: Component: Celerybeat, PR Type: Bugfix
