Repository celery/celery, pull requests merged in 2018-08, with the labels that each got.

#4952 Fix chain.apply (it ignored kwargs) and add unit test
  celery/canvas.py
  t/unit/tasks/test_canvas.py
Labels: Component: Canvas, PR Type: Bugfix

#4746 Add test for ResultSet that includes a deliberate error
  celery/result.py
  t/integration/tasks.py
  t/integration/test_canvas.py
Labels: Category: Results Backend

#4846 Fix BytesWarning in concurrency/asynpool.py
  celery/concurrency/asynpool.py
  celery/platforms.py
Labels: PR Type: Enhancement

#4892 Fixed Issue #4638
  celery/platforms.py
Labels: Operating System: Windows, PR Type: Bugfix

#4970 Add task.acks_on_failure_or_timeout option
  celery/app/task.py
  celery/worker/request.py
  t/unit/worker/test_request.py
Labels: Component: Amazon SQS Broker

#4971 changed x-ha-policy to ha-mode for rabbitmq 3 changes
  celery/app/amqp.py
  t/unit/app/test_amqp.py
Labels: Component: RabbitMQ Broker, PR Type: Enhancement

#4979 Support chords with CELERY_TASK_ALWAYS_EAGER (fix #4873)
  CONTRIBUTORS.txt
  celery/canvas.py
  t/integration/tasks.py
  t/integration/test_canvas.py
  t/unit/tasks/test_canvas.py
Labels: Component: Canvas

#4490 Add task properties to AsyncResult, store in backend
  celery/app/defaults.py
  celery/app/task.py
  celery/backends/base.py
  celery/result.py
  docs/userguide/configuration.rst
  t/unit/backends/test_base.py
  t/unit/tasks/test_result.py
  t/unit/worker/test_request.py
Labels: PR Type: Enhancement, Status: Ready For Merge ✔

#4985 Correct grammar for signals.rst doc
  docs/userguide/signals.rst
Labels: Category: Documentation, PR Type: Bugfix

#4870 allow couchbase to automatically detect serialization format
  celery/backends/couchbase.py
Labels: Component: Couchbase Results Backend, PR Type: Enhancement

#5009 Added an integration test for #1921
  t/integration/test_canvas.py
Labels: Category: Tests, PR Type: Enhancement
