Repository celery/celery, pull requests merged in 2019-07, with the labels that each got.

#5629 Remove Github and Patreon from Github Funding
  .github/FUNDING.yml
Labels: Category: Project Governance, PR Type: Bugfix

#5640 Fix 5028: Added argument.
  docs/userguide/calling.rst
Labels: Category: Documentation

#5638 Fix Nested group(chain(group)) fails
  celery/backends/asynchronous.py
  celery/result.py
  t/integration/test_canvas.py
Labels: Component: Canvas, PR Type: Bugfix
