Repository celery/celery, pull requests merged in 2019-10, with the labels that each got.

#5717 Fix serialization and deserialization of nested exception classes
  celery/backends/base.py
  t/unit/backends/test_base.py
Labels: Category: Results Backend, PR Type: Bugfix

#5759 Fix #5597: chain priority
  celery/canvas.py
  t/integration/tasks.py
  t/integration/test_canvas.py
  t/unit/tasks/test_canvas.py
Labels: Component: Canvas, PR Type: Bugfix

#5769 Fix typo in canvas.rst
  docs/userguide/canvas.rst
Labels: Category: Documentation, PR Type: Cleanup

#5778 Simplify commands to looking for celery worker processes
  docs/faq.rst
  docs/userguide/workers.rst
Labels: Category: Documentation

#5373 Added integration coverage for link_error
  celery/backends/base.py
  requirements/test-integration.txt
  t/integration/conftest.py
  t/integration/tasks.py
  t/integration/test_canvas.py
  t/integration/test_tasks.py
  t/unit/backends/test_base.py
Labels: Category: Tests, Component: Task Execution, PR Type: Bugfix

#5780 Grammar in documentation
  docs/getting-started/next-steps.rst
Labels: Category: Documentation, PR Type: Cleanup

#5790 pypy 7.2 matrix
  .travis.yml
Labels: Category: Project Governance, PR Type: Enhancement

#5791 Pytest 5.x for celery 5
  requirements/test.txt
Labels: Category: Tests

#5773 Fix #5772 task_default_exchange & task_default_exchange_type not work
  celery/app/amqp.py
  t/unit/app/test_amqp.py
Labels: PR Type: Bugfix, pyamqp

#5739 Run integration suite with memcached results backend.
  .travis.yml
  requirements/test-integration.txt
  tox.ini
Labels: Category: Project Governance, PR Type: Enhancement

#5744 Fix test_group_result_not_has_cache for sync backends with native join
  celery/backends/base.py
Labels: Component: Cache Results Backend, Component: Memcached Results Backend, PR Type: Bugfix, Status: Ready For Merge ✔

#5753 Fix regression in PR #5681
  celery/canvas.py
Labels: Component: Azure Block Blob Results Backend, Component: Cache Results Backend, Component: Canvas, Component: DynamoDB Results Backend, PR Type: Bugfix, Status: Ready For Merge ✔

#5795 Fix #5734 Celery does not consider authMechanism on mongodb backend URLs
  celery/backends/mongodb.py
  t/unit/backends/test_mongodb.py
Labels: Component: MongoDB Results Backend, PR Type: Bugfix

#5785 Add Python 3.8 Support
  .travis.yml
  celery/contrib/testing/app.py
  requirements/extras/tblib.txt
  t/unit/tasks/test_result.py
  tox.ini
Labels: Category: Deployment, Category: Project Governance, PR Type: Enhancement

#5801 update docker config
  docker/Dockerfile
  docker/scripts/install-couchbase.sh
Labels: Category: Project Governance, PR Type: Bugfix

#5804 Grammatical & punctuation fixes for CONTRIBUTING.rst document
  CONTRIBUTING.rst
Labels: Category: Documentation
