Repository celery/celery, pull requests merged in 2019-04, with the labels that each got.

#5422 Dockerfile - Upgrade from jessie to stretch
  docker/Dockerfile
  docker/scripts/install-couchbase.sh
Labels: Category: Project Governance, PR Type: Enhancement

#5437 Fix migrate command
  docs/django/first-steps-with-django.rst
Labels: Category: Documentation, PR Type: Bugfix

#5431 Add missing SQS Long Polling info to the docs
  docs/getting-started/brokers/sqs.rst
Labels: Category: Documentation, PR Type: Bugfix

#5443 Stop using pymongo collection deprecated methods
  celery/backends/mongodb.py
  t/unit/backends/test_mongodb.py
Labels: Component: MongoDB Results Backend, PR Type: Enhancement

#5462 Fixed bug 5411
  celery/utils/time.py
  t/unit/utils/test_time.py
Labels: Component: Celerybeat, PR Type: Bugfix

#5428 Add a version switch when importing Mapping
  celery/app/amqp.py
Labels: PR Type: Enhancement

#5435 Attribute Error should be caught in backends base exception
  celery/backends/base.py
  t/unit/backends/test_base.py
Labels: Component: Result Backend, PR Type: Bugfix, Status: Ready For Merge ✔
