Repository celery/celery, pull requests merged in 2019-11, with the labels that each got.

#5813 Update document CONTRIBUTING.rst & fix Dockerfile typo
  CONTRIBUTING.rst
  CONTRIBUTORS.txt
  docker/Dockerfile
Labels: Category: Documentation

#5825 Fix/correct minor doc typos
  CONTRIBUTING.rst
  docs/userguide/concurrency/eventlet.rst
Labels: Category: Documentation

#5820 Preserve the task priority in case of a retry
  celery/app/task.py
  t/integration/tasks.py
  t/integration/test_tasks.py
  t/unit/tasks/test_tasks.py
Labels: PR Type: Bugfix

#5807 events bootstep disabled if no events
  celery/worker/consumer/events.py
  celery/worker/strategy.py
  t/unit/bin/test_worker.py
Labels: PR Type: Bugfix, Status: Needs Test Coverage ✘, events

#5838 The test_nested_group_chain test can run without native_join support
  t/integration/test_canvas.py
Labels: Category: Tests, PR Type: Enhancement

#5834 Run integration tests with Cassandra
  .travis.yml
  celery/backends/cassandra.py
  t/integration/conftest.py
  t/unit/backends/test_cassandra.py
  tox.ini
Labels: Category: Project Governance, Component: Cassandra Results Backend, PR Type: Enhancement

#5843 SQS - Reject on failure
  celery/worker/request.py
  t/unit/worker/test_request.py
Labels: Component: Amazon SQS Broker

#5099 Add a concurrency model with ThreadPoolExecutor
  appveyor.yml
  celery/concurrency/__init__.py
  celery/concurrency/thread.py
  docs/getting-started/introduction.rst
  docs/includes/introduction.txt
  docs/internals/guide.rst
  docs/internals/reference/celery.concurrency.thread.rst
  docs/internals/reference/index.rst
  docs/userguide/workers.rst
  requirements/extras/thread.txt
  requirements/test-ci-base.txt
  requirements/test-ci-default.txt
  t/unit/concurrency/test_thread.py
Labels: PR Type: Enhancement

#5845 Chain primitive's code example fix in canvas documentation (Regressio…
  docs/userguide/canvas.rst
Labels: Category: Documentation, PR Type: Cleanup

#5805 Add auto expiry for DynamoDB backend
  celery/backends/dynamodb.py
  docs/userguide/configuration.rst
  requirements/extras/dynamodb.txt
  t/unit/backends/test_dynamodb.py
Labels: Component: DynamoDB Results Backend, PR Type: Feature

#5851 Skip unsupported canvas when using the cache backend
  t/integration/test_canvas.py
Labels: Component: Canvas

#5661 [Fix #5436] Store extending result in all backends
  celery/backends/base.py
  celery/backends/database/__init__.py
  celery/backends/mongodb.py
  t/unit/backends/test_base.py
  t/unit/backends/test_database.py
Labels: Category: Results Backend, PR Type: Bugfix
