Repository celery/celery, pull requests merged in 2019-03, with the labels that each got.

#5319 Control pattern matching
  celery/app/control.py
  t/unit/app/test_control.py
Labels: PR Type: Feature

#5287 Code improvements
  celery/app/routes.py
  celery/apps/multi.py
  celery/canvas.py
  celery/contrib/testing/manager.py
  celery/events/dumper.py
  celery/worker/consumer/consumer.py
  celery/worker/state.py
Labels: PR Type: Cleanup

#5370 Support PEP 420 namespace packages
  celery/utils/imports.py
  t/unit/utils/test_imports.py
Labels: PR Type: Enhancement

#5378 Added the task_received signal
  Changelog
  celery/signals.py
  celery/worker/strategy.py
  t/unit/worker/test_strategy.py
Labels: Component: Signals, PR Type: Feature

#5382 Added task_acks_on_failure_or_timeout as a setting
  celery/app/defaults.py
  celery/app/task.py
  docs/userguide/configuration.rst
  t/unit/worker/test_request.py
Labels: Category: Documentation, Category: Tests, Component: Task Execution, PR Type: Bugfix

#5374 Bump linter jobs to Python 3.7
  .travis.yml
  requirements/docs.txt
  t/unit/contrib/test_sphinx.py
  tox.ini
Labels: Category: Project Governance, PR Type: Enhancement

#5384 Add documentation for new compression schemes
  docs/userguide/calling.rst
Labels: Category: Documentation, PR Type: Enhancement, Priority: Blocker, Severity: Low, Status: Ready For Merge ✔

#5386 Fix `None` serialization error in Redis backend
  celery/backends/redis.py
  t/unit/backends/test_redis.py
Labels: Component: Redis Results Backend, PR Type: Bugfix

#5387 Fixup redis_backend_use_ssl docs
  docs/userguide/configuration.rst
Labels: Category: Documentation, PR Type: Bugfix

#4744 MongoDB Backend: accept DNS seedlist connection format
  celery/backends/mongodb.py
  requirements/extras/eventlet.txt
  requirements/extras/mongodb.txt
  t/unit/backends/test_mongodb.py
Labels: Component: Eventlet Workers Pool, Component: MongoDB Results Backend, Status: Has Testcase ✔

#5279 requirements: use msgpack instead of msgpack-python
  requirements/extras/msgpack.txt
Labels: PR Type: Enhancement

#5396 Update urls.py because of new version of Django.
  examples/django/proj/urls.py
Labels: Category: Documentation, PR Type: Bugfix

#5399 Allow unregistered signatures to be used as error callbacks
  celery/backends/base.py
  t/unit/backends/test_base.py
Labels: Component: Canvas, PR Type: Bugfix

#5395 Fixes to SSL config handling
  celery/app/base.py
  celery/backends/redis.py
  t/unit/app/test_app.py
  t/unit/backends/test_redis.py
Labels: Component: Redis Broker, Component: Redis Results Backend, PR Type: Bugfix
