Repository celery/celery, pull requests merged in 2019-09, with the labels that each got.

#5730 Use Django's transaction.atomic() in documentation
  docs/userguide/tasks.rst
Labels: PR Type: Cleanup

#5737 celery#5736, Fix disable_sync_subtasks not respected in ResultSet
  celery/result.py
  t/unit/tasks/test_result.py
Labels: Category: Results Backend, PR Type: Bugfix

#5742 Added an integration test that checks if a large group executes correctly
  t/integration/test_canvas.py
Labels: Category: Tests, PR Type: Enhancement

#5442 #5409: remove stale pidfile for non privileged user
  celery/platforms.py
  t/unit/utils/test_platforms.py
Labels: Category: Deployment, PR Type: Bugfix

#5747 Add links to configuration docs from Django first steps
  CONTRIBUTORS.txt
  docs/django/first-steps-with-django.rst
Labels: Category: Documentation

#5749 Test chords with large headers
  t/integration/test_canvas.py
Labels: Category: Tests, PR Type: Enhancement

#5752 Correcting Attribute Name for Task Name
  celery/backends/database/__init__.py
  t/unit/backends/test_database.py
Labels: Component: SQLAlchemy Database Results Backend, PR Type: Bugfix, Status: Needs Test Coverage ✘
