Repository celery/celery, pull requests merged in 2019-08, with the labels that each got.

#5653 Fix: 5080
  docs/reference/celery.app.amqp.rst
Labels: Category: Documentation, PR Type: Bugfix

#5671 Fix termination of asynloop
  celery/worker/loops.py
  celery/worker/state.py
  t/unit/worker/test_loops.py
  t/unit/worker/test_state.py
Labels: PR Type: Bugfix

#5110 Fix migrate task to work with both v1 and v2 of the message protocol
  celery/contrib/migrate.py
  t/unit/contrib/test_migrate.py
Labels: PR Type: Cleanup

#5664 Fixes #5617
  celery/app/amqp.py
  celery/utils/collections.py
  t/unit/app/test_amqp.py
Labels: PR Type: Bugfix, PR Type: Enhancement

#5680 i-5676(fix): fix unit test test_MongoBackend
  t/unit/backends/test_mongodb.py
Labels: Category: Tests, Component: MongoDB Results Backend, PR Type: Bugfix

#5682 Fix canvases which used to raise an exception whenever subsequent groups are chained one after another
  celery/canvas.py
  t/integration/test_canvas.py
Labels: Component: Canvas, PR Type: Bugfix

#5679 UT: add unit test for ResultSet.join_native
  t/unit/tasks/test_result.py
Labels: Category: Tests, PR Type: Enhancement

#5681 Fixed a bug where canvases with a group and tasks in the middle followed by a group fails to complete and indefinitely hangs
  celery/canvas.py
  t/integration/tasks.py
  t/integration/test_canvas.py
Labels: Component: Canvas, PR Type: Bugfix

#5689 removed python 2 compatibility decorator
  celery/app/base.py
  celery/app/defaults.py
  celery/app/task.py
  celery/backends/database/models.py
  celery/beat.py
  celery/bin/base.py
  celery/bin/graph.py
  celery/canvas.py
  celery/contrib/migrate.py
  celery/events/state.py
  celery/exceptions.py
  celery/result.py
  celery/schedules.py
  celery/task/base.py
  celery/utils/collections.py
  celery/utils/dispatch/signal.py
  celery/utils/graph.py
  celery/utils/serialization.py
  celery/utils/term.py
  celery/utils/threads.py
  celery/utils/time.py
  celery/worker/consumer/consumer.py
  celery/worker/request.py
  celery/worker/worker.py
  t/unit/app/test_log.py
  t/unit/utils/test_local.py
  t/unit/utils/test_saferepr.py
  t/unit/worker/test_loops.py
Labels: Version: 5.0

#5291 Make result backend 'prefix-configurable'
  celery/app/utils.py
Labels: Category: Results Backend

#5694 Fix issue with `RuntimeError: OrderedDict mutated during iteration`
  celery/events/state.py
  t/unit/events/test_state.py
Labels: PR Type: Bugfix, events

#5698 Update testing doc
  docs/userguide/testing.rst
Labels: PR Type: Cleanup

#5700 Fixes #5106: Retry WorkerLostError fix for canvas
  celery/worker/request.py
  t/unit/tasks/test_result.py
  t/unit/worker/test_request.py
Labels: Component: Canvas, Component: Task Execution, PR Type: Bugfix
