Repository celery/celery, pull requests merged in 2020-12, with the labels that each got.

#6516 Reintroduce support for custom preload options
  celery/bin/amqp.py
  celery/bin/base.py
  celery/bin/beat.py
  celery/bin/call.py
  celery/bin/celery.py
  celery/bin/control.py
  celery/bin/events.py
  celery/bin/graph.py
  celery/bin/list.py
  celery/bin/logtool.py
  celery/bin/migrate.py
  celery/bin/multi.py
  celery/bin/purge.py
  celery/bin/result.py
  celery/bin/shell.py
  celery/bin/upgrade.py
  celery/bin/worker.py
  docs/userguide/extending.rst
Labels: Category: Documentation, Component: CLI, PR Type: Bugfix

#6523 Added integration tests for calling a task
  t/integration/tasks.py
  t/integration/test_tasks.py
Labels: Category: Tests, PR Type: Enhancement

#6524 DummyClient of cache+memory:// backend now shares state between threads
  celery/backends/cache.py
  t/unit/backends/test_cache.py
Labels: Component: Cache Results Backend, PR Type: Bugfix

#6532 Change deprecated from collections import Mapping/MutableMapping to from collections.abc import ...
  t/unit/utils/test_collections.py
Labels: Category: Tests, PR Type: Enhancement

#6537 Fix type error in S3 backend
  celery/backends/s3.py
  t/unit/backends/test_s3.py
Labels: PR Type: Bugfix, S3 Result backend

#6543 events.py: Remove duplicate decorator in wrong place
  celery/bin/events.py
Labels: Component: CLI, PR Type: Bugfix

#6551 Add sentinel_kwargs to Redis Sentinel docs
  docs/getting-started/brokers/redis.rst
Labels: Category: Documentation

#6544 Depend on the maintained python-consul2 library
  requirements/extras/consul.txt
Labels: Component: Consul Results Backend, PR Type: Enhancement

#6557 Light Backends and Brokers Guides - PR from issue #6539
  docs/getting-started/backends-and-brokers/index.rst
  docs/getting-started/backends-and-brokers/rabbitmq.rst
  docs/getting-started/backends-and-brokers/redis.rst
  docs/getting-started/backends-and-brokers/sqs.rst
  docs/getting-started/brokers/index.rst
  docs/getting-started/index.rst
Labels: Category: Documentation

#6568 Mention rpc:// backend in Backend and Brokers page
  docs/getting-started/backends-and-brokers/index.rst
Labels: Category: Documentation

#6570 Fix information about rpc:// backend
  docs/getting-started/backends-and-brokers/index.rst
Labels: Category: Documentation
