Repository celery/celery, pull requests merged in 2020-10, with the labels that each got.

#6365 Restore the celery worker --without-{gossip,mingle,heartbeat} flags
  celery/bin/worker.py
Labels: Component: CLI, PR Type: Bugfix

#6383 Provide clearer error messages when app fails to load.
  celery/bin/celery.py
Labels: Component: CLI, PR Type: Enhancement

#6387 fix pytest plugin registration documentation
  docs/userguide/testing.rst
Labels: Category: Documentation, PR Type: Bugfix

#6385 Contains a workaround for the capitalized configuration issue
  celery/apps/worker.py
Labels: Component: Configuration, PR Type: Bugfix

#6390 Remove old explanation regarding `absolute_import`
  docs/django/first-steps-with-django.rst
Labels: Category: Documentation, PR Type: Enhancement

#6392 Update canvas.rst
  docs/userguide/canvas.rst
Labels: Category: Documentation, Component: Canvas, PR Type: Enhancement

#6398 Remove duplicate words from docs
  docs/getting-started/introduction.rst
Labels: Category: Documentation, PR Type: Bugfix

#6396 Allow lowercase log levels.
  celery/bin/base.py
Labels: Component: CLI, PR Type: Bugfix

#6394 Detach now correctly passes options with more than one word.
  celery/bin/worker.py
Labels: Component: CLI, PR Type: Bugfix, Version: 5.0

#6388 The celery multi command now works as expected
  celery/apps/multi.py
  celery/bin/multi.py
  requirements/test-ci-default.txt
  t/unit/apps/test_multi.py
Labels: Category: Deployment, Component: CLI, PR Type: Bugfix, Version: 5.0

#6408 Fixed loglevel info->INFO in docs
  docs/django/first-steps-with-django.rst
  docs/getting-started/next-steps.rst
  docs/userguide/application.rst
  docs/userguide/calling.rst
  docs/userguide/debugging.rst
  docs/userguide/workers.rst
  examples/app/myapp.py
  examples/django/README.rst
  examples/eventlet/README.rst
  examples/periodic-tasks/myapp.py
  examples/security/mysecureapp.py
Labels: Category: Documentation

#6401 Rewrite detaching logic
  celery/apps/multi.py
  celery/bin/worker.py
  docs/userguide/daemonizing.rst
  extra/systemd/celery.service
  extra/systemd/celerybeat.service
Labels: Category: Deployment, Component: CLI, PR Type: Bugfix, Version: 5.0

#6411 fix: Pass back real result for single task chains
  celery/canvas.py
  t/integration/test_canvas.py
  t/unit/tasks/test_canvas.py
Labels: Component: Canvas, PR Type: Bugfix
