Repository celery/celery, pull requests merged in 2020-07, with the labels that each got.

#6187 test_canvas: Add test for chord-in-chain
  t/integration/test_canvas.py
Labels: Category: Tests, Component: Canvas, PR Type: Test Case

#6222 Remove mutable arguments in assert_routes_to_queue
  t/unit/app/test_routes.py
Labels: Category: Tests, PR Type: Cleanup

#6223 FIX: -A and --args should behave the same.
  celery/bin/base.py
  celery/bin/celery.py
  t/unit/bin/test_base.py
  t/unit/bin/test_celery.py
Labels: PR Type: Bugfix

#6233 Class-based tasks autoretry
  celery/app/autoretry.py
  celery/app/base.py
  celery/app/registry.py
  celery/contrib/pytest.py
  t/integration/conftest.py
  t/integration/tasks.py
  t/integration/test_tasks.py
  t/unit/tasks/test_tasks.py
Labels: PR Type: Bugfix

#6218 Preserve order of group results with Redis result backend
  celery/app/amqp.py
  celery/app/base.py
  celery/app/task.py
  celery/backends/redis.py
  celery/canvas.py
  celery/utils/abstract.py
  celery/worker/request.py
  t/integration/test_canvas.py
  t/unit/backends/test_redis.py
  t/unit/tasks/test_canvas.py
  t/unit/worker/test_request.py
Labels: Component: Redis Results Backend, PR Type: Bugfix

#6246 fix: Make development docker image build again
  docker/Dockerfile
Labels: Category: Project Governance

#6251 replace future with celery.five Fixes #6250, and reraise to include outer tracebacks
  celery/backends/base.py
  requirements/default.txt
Labels: PR Type: Enhancement

#6264 fix LTGM Alert: Module '...' is imported with both 'import' and 'imp…
  celery/__init__.py
  celery/backends/asynchronous.py
  celery/backends/redis.py
  celery/backends/riak.py
  t/unit/concurrency/test_gevent.py
Labels: PR Type: Cleanup

#6245 improv: Make use of ordered sets in Redis opt-in
  celery/backends/redis.py
  docs/getting-started/brokers/redis.rst
  t/integration/test_canvas.py
  t/unit/backends/test_redis.py
Labels: Component: Redis Results Backend, PR Type: Enhancement
