Repository celery/celery, pull requests merged in 2020-05, with the labels that each got.

#5758 Allow start_worker to function without ping task
  celery/contrib/testing/worker.py
Labels: Category: Tests, PR Type: Bugfix

#6078 [Fix #6074]: Add missing documentation for MongoDB as result backend.
  docs/getting-started/first-steps-with-celery.rst
  docs/userguide/configuration.rst
Labels: Category: Documentation

#6088 try ubuntu focal
  .travis.yml
Labels: Category: Project Governance

#6098 pypy3
  setup.py
Labels: Category: Project Governance

#6103 Always requeue while worker lost regardless of the redelivered flag
  celery/worker/request.py
  t/unit/worker/test_request.py
Labels: PR Type: Bugfix

#6105 Fixbug: self.result may not be a subclass of BaseException
  celery/result.py
Labels: PR Type: Bugfix

#5199 Update time.py to solve the microsecond issues
  celery/utils/time.py
Labels: PR Type: Bugfix, Status: Needs Test Coverage ✘

#5767 Add priority support for 'celery.chord_unlock' task (#5766)
  celery/backends/base.py
Labels: Component: Canvas, PR Type: Enhancement, Status: Needs Documentation ✘, Status: Needs Test Coverage ✘

#6109 Change eager retry behaviour
  celery/app/task.py
  celery/exceptions.py
  t/unit/tasks/test_tasks.py
Labels: PR Type: Bugfix

#6115 Avoid race condition in elasticsearch backend
  celery/backends/elasticsearch.py
  t/unit/backends/test_elasticsearch.py
Labels: Component: ElasticSearch Results Backend, PR Type: Bugfix
