Repository celery/celery, pull requests merged in 2021-09, with the labels that each got.

#6899 fix: Pass a `Context` when chaining fail results
  celery/backends/base.py
Labels: Component: Canvas, Status: Needs Testcase ✘, Component: RPC Results Backend, Status: Needs Verification ✘, PR Type: Bugfix, Component: Task Execution

#6942 Kill all workers when main process exits in prefork model
  celery/concurrency/prefork.py
  celery/platforms.py
  t/unit/concurrency/test_prefork.py
  t/unit/utils/test_platforms.py
Labels: Component: Prefork Workers Pool, PR Type: Enhancement

#6947 test kombu 5.2.0rc1
  requirements/default.txt
Labels: Category: Tests

#6948 try moto 2.2.x
  requirements/test.txt
Labels: Category: Tests

#6779 Prepared Hacker News Post on Release Action
  .github/workflows/post_release_to_hacker_news.yml
Labels: Category: Packaging and Release Management, Category: Project Governance

#6949 update setup with python 3.7 as minimum
  setup.py
Labels: Category: Project Governance

#6946 Added note about automatic killing all child processes of worker after its termination
  docs/userguide/workers.rst
Labels: Category: Documentation

#6956 Move importskip before greenlet import
  t/unit/concurrency/test_eventlet.py
Labels: Category: Tests

#6957 amqp: send expiration field to broker if requested by user
  celery/app/base.py
  t/unit/tasks/test_tasks.py
Labels: PR Type: Enhancement

#6955 Single line drift warning
  celery/events/state.py
Labels: PR Type: Enhancement

#6959 canvas: fix kwargs argument to prevent recursion (#6810)
  celery/canvas.py
  t/unit/tasks/test_chord.py
Labels: Component: Canvas, PR Type: Bugfix

#6916 Give indication whether the task is replacing another
  celery/app/task.py
  celery/worker/request.py
  docs/internals/protocol.rst
  docs/userguide/tasks.rst
  t/unit/tasks/test_canvas.py
  t/unit/tasks/test_tasks.py
Labels: Component: Canvas, PR Type: Enhancement, Status: Has Test Coverage ✔, Status: Has Documentation✔

#6971 Bump Python 3.10.0 to rc2
  .github/workflows/python-package.yml
Labels: Category: Project Governance, PR Type: Enhancement
