Repository celery/celery, pull requests merged in 2021-05, with the labels that each got.

#6750 Add support in the redis result backend for authenticating with a username
  celery/app/defaults.py
  celery/backends/redis.py
  docs/userguide/configuration.rst
  t/unit/backends/test_redis.py
Labels: Component: Redis Results Backend, PR Type: Enhancement

#6711 worker_pool setting is now respected correctly
  celery/app/base.py
  celery/bin/worker.py
  t/unit/app/test_app.py
Labels: Component: CLI, Component: Configuration, PR Type: Bugfix, Status: Needs Backporting, Status: Needs Test Coverage ✘

#6752 update docs/userguide - `@task` -> `@app.task`
  docs/userguide/tasks.rst
Labels: Category: Documentation, PR Type: Bugfix

#6757 Celery Mailbox accept and serializer parameters are initialized from configuration
  celery/app/control.py
  t/unit/app/test_control.py
Labels: Component: Task Serialization, inspect

#6765 fix: Sanitization of passwords in sentinel URIs
  celery/backends/redis.py
  t/unit/backends/test_redis.py
Labels: Component: Redis Results Backend, PR Type: Bugfix

#6758 Add LOG_RECEIVED to customize logging
  celery/app/trace.py
  celery/worker/strategy.py
  docs/userguide/extending.rst
  t/unit/worker/test_strategy.py
Labels: Component: Logging, PR Type: Enhancement

#6762 Add What's new for v5.1.0
  Changelog.rst
  README.rst
  celery/__init__.py
  docs/history/index.rst
  docs/history/whatsnew-5.0.rst
  docs/index.rst
  docs/whatsnew-5.1.rst
Labels: Category: Documentation, Category: Project Governance, PR Type: Enhancement

#6775 Update wall of contributors
  docs/whatsnew-5.1.rst
Labels: Category: Project Governance, PR Type: Cleanup

#6774 fix: Have evcam accept kwargs
  celery/events/snapshot.py
Labels: Component: CLI, PR Type: Bugfix, Status: Needs Backporting

#6787 Fix '--pool=threads' support in command line options parsing
  celery/__init__.py
  celery/bin/worker.py
  celery/concurrency/__init__.py
  t/unit/concurrency/test_concurrency.py
Labels: Component: CLI, PR Type: Bugfix

#6791 fix: `LoggingProxy.write()` return type
  celery/utils/log.py
  t/unit/app/test_log.py
Labels: Component: Logging, PR Type: Bugfix
