Repository celery/celery, pull requests merged in 2021-12, with the labels that each got.

#7146 Exclude pypy-windows checks from CI temporarily
  .github/workflows/python-package.yml
  t/unit/backends/test_mongodb.py
Labels: Category: Project Governance, PR Type: Bugfix

#7167 Docs for SQS: setting additional message properties
  docs/getting-started/backends-and-brokers/sqs.rst
Labels: PR Type: Bugfix, Category: Documentation

#7135 Split Signature.__or__ into subclasses' __or__
  celery/canvas.py
  t/unit/tasks/test_canvas.py
Labels: Component: Canvas, PR Type: Enhancement

#7184 Fix typo in documentation
  docs/django/first-steps-with-django.rst
Labels: Category: Documentation

#7186 add memory usage section to optimizing docs
  docs/userguide/optimizing.rst
Labels: Category: Documentation

#7194 try newer bumped versions
  requirements/default.txt
Labels: Category: Packaging and Release Management
