Repository celery/celery, pull requests merged in 2021-07, with the labels that each got.

#6835 Fix docstring for Signal.send to match code
  celery/utils/dispatch/signal.py
Labels: Category: Documentation

#6843 Use the dropseed/changerelease action to sync changelog to GitHub Releases
  .github/workflows/changerelease.yml
Labels: Category: Packaging and Release Management

#6849 Fix #6844 by allowing safe queries via app.inspect().active().
  celery/app/control.py
  celery/worker/control.py
  celery/worker/request.py
  t/unit/app/test_control.py
  t/unit/worker/test_control.py
  t/unit/worker/test_request.py
Labels: PR Type: Bugfix

#6848 Fix Open Collective donate button
  docs/_templates/sidebardonations.html
Labels: Category: Documentation, PR Type: Bugfix

#6853 Fix setting worker concurrency option after signal
  celery/app/defaults.py
Labels: Component: CLI, PR Type: Bugfix

#6784 Make `ResultSet.on_ready` promise hold a weakref to self
  celery/result.py
Labels: Component: Canvas, PR Type: Bugfix

#6860 Update configuration.rst
  docs/userguide/configuration.rst
Labels: Category: Documentation

#6863 Discard jobs on flush if synack isn't enabled
  celery/concurrency/asynpool.py
Labels: Component: Prefork Workers Pool, PR Type: Bugfix

#6861 relaxed click version
  celery/bin/base.py
  celery/bin/worker.py
  requirements/default.txt
Labels: Category: Tests, Component: CLI

#6837 doc: Amend IRC network link to Libera
  README.rst
Labels: Category: Documentation, Priority: Trivial

#6867 test on 3.10.b4
  .github/workflows/python-package.yml
Labels: Category: Project Governance, PR Type: Enhancement

#6866 fix inspect --json output to return valid json without --quiet
  celery/bin/control.py
Labels: Component: CLI, PR Type: Bugfix

#6886 Fix typo in mark_as_failure
  celery/backends/base.py
Labels: Category: Results Backend
