Repository celery/celery, pull requests merged in 2021-11, with the labels that each got.

#6939 5.2 Release
  Changelog.rst
  docs/history/changelog-5.1.rst
  docs/history/index.rst
  docs/history/whatsnew-5.1.rst
  docs/includes/resources.txt
  docs/index.rst
  docs/whatsnew-5.2.rst
Labels: Issue Type: Task, Category: Project Governance

#7037 Bump kombu to version 5.2.0
  requirements/default.txt
Labels: Category: Project Governance, PR Type: Enhancement

#7025 Fix typos
  celery/app/autoretry.py
  celery/concurrency/asynpool.py
  celery/contrib/pytest.py
  celery/loaders/base.py
  celery/utils/functional.py
  celery/utils/text.py
  celery/utils/threads.py
  docker/Dockerfile
  docs/history/changelog-4.4.rst
  docs/history/whatsnew-3.0.rst
  docs/history/whatsnew-4.4.rst
  extra/generic-init.d/celerybeat
  t/unit/backends/test_redis.py
  t/unit/tasks/test_canvas.py
  t/unit/utils/test_collections.py
  t/unit/worker/test_worker.py
Labels: PR Type: Cleanup, Category: Documentation

#7042 try new latest version 12.9.0
  requirements/extras/azureblockblob.txt
Labels: Component: Azure Block Blob Results Backend, CI

#7044 update to new django settings
  examples/celery_http_gateway/settings.py
Labels: PR Type: Cleanup, Category: Documentation

#7043 fix register_task method
  celery/app/base.py
Labels: PR Type: Bugfix

#7051 Add pymongo issue to "What's new in Celery 5.2"
  docs/whatsnew-5.2.rst
Labels: PR Type: Cleanup, Category: Documentation

#6980 Fire task failure signal on final reject
  celery/worker/request.py
  t/unit/worker/test_request.py
Labels: PR Type: Enhancement, Component: Signals, Component: Task Execution

#7053 update kombu to 5.2.1
  requirements/default.txt
Labels: Category: Packaging and Release Management

#7058 Remove unused failing unittest
  t/distro/test_CI_reqs.py
Labels: Category: Tests, PR Type: Cleanup

#7060 add toml file path
  .github/workflows/python-package.yml
Labels: CI

#7057 Fix rstrip usage on bytes instance in ProxyLogger.
  celery/utils/log.py
  t/unit/app/test_log.py
Labels: Component: Logging, PR Type: Bugfix

#7055 Pass logfile to ExecStop in celery.service example systemd file
  docs/userguide/daemonizing.rst
Labels: Category: Deployment, Category: Documentation

#7059 Move pytest configuration from setup.cfg to pyproject.toml
  pyproject.toml
  setup.cfg
Labels: Category: Tests, PR Type: Cleanup

#7066 not needed as python 2 is not supported.
  requirements/pkgutils.txt
Labels: PR Type: Cleanup, CI

#7068 drop as we don't use travis anymore
  requirements/test-ci-base.txt
Labels: PR Type: Cleanup, CI

#7067 simplejson is not used anymore
  requirements/test-integration.txt
Labels: PR Type: Cleanup, CI

#7077 Remove dependency to case
  celery/contrib/testing/mocks.py
  pyproject.toml
  requirements/test.txt
  t/unit/app/test_app.py
  t/unit/app/test_builtins.py
  t/unit/app/test_loaders.py
  t/unit/app/test_log.py
  t/unit/app/test_schedules.py
  t/unit/backends/test_cache.py
  t/unit/backends/test_cassandra.py
  t/unit/backends/test_mongodb.py
  t/unit/backends/test_redis.py
  t/unit/concurrency/test_prefork.py
  t/unit/conftest.py
  t/unit/contrib/test_migrate.py
  t/unit/events/test_snapshot.py
  t/unit/fixups/test_django.py
  t/unit/security/test_certificate.py
  t/unit/security/test_security.py
  t/unit/tasks/test_tasks.py
  t/unit/utils/test_platforms.py
  t/unit/utils/test_serialization.py
  t/unit/utils/test_threads.py
  t/unit/worker/test_autoscale.py
  t/unit/worker/test_consumer.py
  t/unit/worker/test_worker.py
Labels: Category: Tests, CI

#7065 fix: task expiration is timezone aware if needed
  CONTRIBUTORS.txt
  celery/app/base.py
  t/unit/tasks/test_tasks.py
Labels: PR Type: Bugfix

#7078 minor weaks to github actions
  .github/workflows/python-package.yml
  requirements/extras/couchbase.txt
  requirements/extras/eventlet.txt
  requirements/extras/gevent.txt
  requirements/extras/redis.txt
Labels: PR Type: Cleanup, CI

#7094 pin redis below v4.0.0 for now to fix kombu
  requirements/extras/redis.txt
Labels: redis-py, CI

#7096 bump minimum kombu version to 5.2.2
  requirements/default.txt
Labels: Category: Packaging and Release Management, CI

#7101 Comments and questions on celery/canvas.py
  celery/canvas.py
Labels: Component: Canvas, PR Type: Cleanup

#7112 create codeql beta
  .github/workflows/codeql-analysis.yml
Labels: Category: Packaging and Release Management, Category: Project Governance, CI

#6995 start with switching to debian slim image
  docker/Dockerfile
  docker/docker-compose.yml
  docker/docs/Dockerfile
  docker/scripts/install-pyenv.sh
Labels: Category: Tests, Component: Docker Image

#7119 space-added
  celery/bin/worker.py
Labels: PR Type: Cleanup, Category: Documentation

#7120 unpin redis
  requirements/extras/redis.txt
Labels: redis-py, CI

#6998 try pypy3.8 beta
  .github/workflows/python-package.yml
Labels: Category: Tests, CI
