Repository celery/celery, pull requests merged in 2021-10, with the labels that each got.

#6975 Prevent worker to send expired revoked items upon hello command
  celery/worker/control.py
  t/unit/worker/test_control.py
Labels: Component: Gossip, PR Type: Enhancement

#6979 docs: clarify the 'keeping results' section
  docs/getting-started/first-steps-with-celery.rst
Labels: PR Type: Enhancement, Category: Documentation

#6981 Update deprecated task module removal in 5.0 documentation
  docs/history/whatsnew-5.0.rst
  docs/internals/deprecation.rst
  docs/whatsnew-5.1.rst
Labels: PR Type: Cleanup, Category: Documentation

#6983 Documenting the default consumer_timeout value for rabbitmq >= 3.8.15
  docs/userguide/calling.rst
Labels: Category: Deployment, Component: RabbitMQ Broker, PR Type: Bugfix, Category: Documentation

#6978 Azure blockblob backend parametrized connection/read timeouts
  celery/app/defaults.py
  celery/backends/azureblockblob.py
  docs/userguide/configuration.rst
  t/unit/backends/test_azureblockblob.py
Labels: Component: Azure Block Blob Results Backend
