Repository celery/celery, pull requests merged in 2021-04, with the labels that each got.

#6703 chek if billiard v3.6.4.0 pass tests
  requirements/default.txt
Labels: Category: Packaging and Release Management, Category: Tests

#6706 test with kombu v5.1.0b1
  requirements/default.txt
Labels: Category: Packaging and Release Management, Category: Tests

#6561 original dict subclass replaced with a plain dict after sanity checking the keys
  celery/app/amqp.py
Labels: Component: Task Serialization, PR Type: Bugfix

#6708 Fix CI Failure
  .github/workflows/python-package.yml
Labels: Category: Project Governance, PR Type: Bugfix

#6709 Add support for SQLAlchemy 1.4
  celery/backends/database/session.py
Labels: Component: SQLAlchemy Database Results Backend, PR Type: Enhancement

#6720 fix AttributeError regression in #6619
  celery/beat.py
  t/unit/app/test_beat.py
Labels: Component: Celerybeat, PR Type: Bugfix

#6713 `some_task.apply_async(ignore_result=True)` now avoids persisting the result
  celery/app/amqp.py
  celery/app/base.py
  celery/app/task.py
  celery/backends/base.py
  celery/worker/request.py
  t/integration/test_tasks.py
  t/unit/worker/test_request.py
Labels: Category: Results Backend, Component: Task Execution, PR Type: Bugfix, PR Type: Feature, Status: Has Documentation✔, Status: Has Test Coverage ✔

#6688 Update systemd tmpfiles path
  docs/userguide/daemonizing.rst
Labels: Category: Deployment, PR Type: Enhancement

#6740 Fixed incorrect coding style (textwidth) in ./app
  celery/app/base.py
  celery/app/task.py
  celery/app/utils.py
Labels: PR Type: Cleanup

#6743 Minor changes to the django/proj/celery.py example
  examples/django/proj/celery.py
Labels: Category: Documentation, PR Type: Cleanup

#6741 Ensure AMQPContext exposes an app attribute
  celery/bin/amqp.py
Labels: Component: CLI, PR Type: Bugfix, Status: Needs Backporting

#6710 Inspect commands now accept arguments
  celery/bin/control.py
Labels: Component: CLI, PR Type: Bugfix, Status: Needs Backporting

#6733 fix: Chord counting of group children
  celery/canvas.py
  t/integration/test_canvas.py
  t/unit/tasks/test_canvas.py
Labels: Component: Canvas, PR Type: Bugfix, Priority: Blocker, Status: Needs Test Coverage ✘

#6745 Update periodic-tasks.rst : add "add" task in the example
  docs/userguide/periodic-tasks.rst
Labels: Category: Documentation, PR Type: Enhancement

#6654 Terminate tasks with late acknoledgement on connection loss
  celery/app/defaults.py
  celery/bin/amqp.py
  celery/worker/consumer/consumer.py
  celery/worker/request.py
  docs/userguide/configuration.rst
  t/unit/worker/test_consumer.py
  t/unit/worker/test_request.py
Labels: Component: Consumer, Component: Task Execution, PR Type: Bugfix, Status: Has Documentation✔, Status: Has Test Coverage ✔

#6722 Deduplicate successful tasks
  celery/app/defaults.py
  celery/app/trace.py
  celery/worker/request.py
  celery/worker/state.py
  docs/userguide/configuration.rst
  t/unit/tasks/test_trace.py
Labels: Component: Task Execution, PR Type: Feature, Priority: Major, Status: Has Documentation✔, Status: Has Test Coverage ✔

#6749 #6748 Fix Retry.__reduce__ method
  celery/exceptions.py
  t/unit/app/test_exceptions.py
Labels: Component: Task Serialization, PR Type: Bugfix
