Repository celery/celery, pull requests merged in 2022-10, with the labels that each got.

#7728 Update ambiguous acks_late doc
  celery/app/task.py
  docs/history/changelog-1.0.rst
  docs/userguide/configuration.rst
Labels: Category: Documentation

#7814 Remove `isatty` wrapper function
  celery/app/log.py
  celery/apps/worker.py
  celery/platforms.py
  celery/utils/term.py
  t/unit/utils/test_platforms.py
Labels: PR Type: Cleanup

#7813 Remove unused variable `_range`
  celery/platforms.py
Labels: PR Type: Cleanup

#7826 Remove `.coveragerc` file
  .coveragerc
  pyproject.toml
Labels: PR Type: Cleanup

#7837 Stabilized test_mutable_errback_called_by_chord_from_group_fail_multiple
  t/integration/test_canvas.py
Labels: PR Type: Test Case

#7838 New control command `revoke_by_stamped_headers`
  celery/app/control.py
  celery/result.py
  celery/worker/control.py
  celery/worker/request.py
  celery/worker/state.py
  docs/userguide/workers.rst
  requirements/test.txt
  t/integration/test_tasks.py
  t/unit/app/test_control.py
  t/unit/worker/test_control.py
  t/unit/worker/test_state.py
Labels: PR Type: Enhancement, Worker

#7856 Removed the mandatory requirement to include `stamped_headers` key when implementing `on_signature()`
  celery/canvas.py
  docs/userguide/canvas.rst
  t/integration/test_tasks.py
  t/unit/tasks/test_canvas.py
Labels: PR Type: Enhancement
