Repository celery/celery, pull requests merged in 2022-03, with the labels that each got.

#7330 try new major release of pytest 7
  requirements/test.txt
Labels: Category: Tests, CI

#7257 Remove __ne__ methods
  celery/beat.py
  celery/events/state.py
  celery/result.py
  celery/schedules.py
  celery/utils/collections.py
Labels: PR Type: Cleanup

#7244 fix #7200 uid and gid
  celery/bin/worker.py
Labels: PR Type: Bugfix

#7339 worker: Fix warm shutdown hanging due to timing of signal handler
  celery/apps/worker.py
Labels: Worker Hangs, PR Type: Bugfix
