Repository celery/celery, pull requests merged in 2022-01, with the labels that each got.

#7196 update docs
  docs/userguide/tasks.rst
Labels: PR Type: Cleanup, Category: Documentation

#7205 Remove Python 3.4 compatibility code
  celery/utils/saferepr.py
Labels: PR Type: Cleanup

#7209 update docs to fix #7203
  docs/userguide/tasks.rst
Labels: PR Type: Cleanup, Category: Documentation

#7220 call ping to set connection for avoiding error (take place of #7215)
  celery/backends/redis.py
Labels: Component: Redis Results Backend, PR Type: Bugfix

#7223 Documentation updates related to task names
  docs/userguide/periodic-tasks.rst
  docs/userguide/tasks.rst
Labels: Component: Celerybeat, Category: Documentation

#7218 Use importlib instead of discouraged pkg_resources
  celery/app/backends.py
  celery/beat.py
  celery/bin/celery.py
  celery/utils/imports.py
  docs/userguide/extending.rst
  requirements/default.txt
Labels: Category: Packaging and Release Management, Component: CLI, CI

#7234 Clarify relation between visibility timeout & predefined queues in SQS
  docs/getting-started/backends-and-brokers/sqs.rst
Labels: Component: Kombu, Component: Amazon SQS Broker, PR Type: Enhancement, Category: Documentation

#7246 fix #7245 remove duplicated uid in command params
  celery/bin/base.py
Labels: PR Type: Bugfix

#7262 fix typo in exception
  celery/backends/base.py
Labels: PR Type: Cleanup, Category: Results Backend

#7243 Annotate test failures in PRs
  requirements/test-ci-base.txt
Labels: Category: Project Governance, PR Type: Enhancement, CI
