Repository celery/celery, pull requests merged in 2022-08, with the labels that each got.

#7609 Make default worker state limits configurable
  celery/worker/state.py
  docs/userguide/workers.rst
  t/unit/worker/test_state.py
Labels: PR Type: Enhancement, PR Type: Feature

#7675 Fix unknown task error typo
  celery/worker/consumer/consumer.py
Labels: Category: Documentation

#7730 Fixed bug in chord stamping with another chord as a body + unit test
  celery/canvas.py
  t/unit/tasks/test_canvas.py
Labels: Component: Canvas, PR Type: Bugfix
