Repository celery/celery, pull requests merged in 2022-05, with the labels that each got.

#7504 modify libs and os
  .github/workflows/python-package.yml
Labels: CI

#7503 Make start_worker, setup_default_app reusable outside of pytest
  celery/contrib/testing/app.py
  celery/contrib/testing/worker.py
  t/unit/contrib/test_worker.py
Labels: Component: Pytest Integration

#7447 Ensure a proper error message is raised when id for key is empty
  celery/backends/base.py
  t/unit/backends/test_base.py
Labels: PR Type: Enhancement, Category: Results Backend

#7541 Add notes about ignore_result attribute regarding canvas
  docs/userguide/canvas.rst
  docs/userguide/tasks.rst
Labels: Category: Documentation
