Repository celery/celery, pull requests merged in 2022-04, with the labels that each got.

#7395 Annotate `celery/states.py`
  celery/states.py
  pyproject.toml
Labels: PR Type: Enhancement

#7400 Ignore coverage on `TYPE_CHECKING`
  pyproject.toml
Labels: CI

#7404 Hotfix: Expose more debugging information when receiving unkown tasks
  celery/worker/consumer/consumer.py
Labels: Component: Logging, PR Type: Enhancement

#7405 Expose more debugging information when receiving unkown tasks
  celery/worker/consumer/consumer.py
Labels: Component: Logging, PR Type: Enhancement

#7431 Backport #7406 to 5.2
  Changelog.rst
  celery/utils/imports.py
Labels: Priority: Critical, Severity: Critical, PR Type: Bugfix

#7433 Backport 7406
  Changelog.rst
  celery/utils/imports.py
Labels: Priority: Critical, Severity: Critical, Issue Type: Bug Report

#7443 Avoid negating a constant in a loop.
  celery/result.py
Labels: PR Type: Enhancement, Category: Performance

#7385 Ensure expiration is of float type when migrating tasks
  celery/contrib/migrate.py
Labels: PR Type: Bugfix, Component: Task Execution, Component: Task Serialization

#7457 fix userguide deamonizing by changing the systemd --version by system…
  docs/userguide/daemonizing.rst
Labels: PR Type: Bugfix, Category: Documentation

#7406 load_extension_class_names - correct module_name
  celery/utils/imports.py
Labels: Priority: Critical, Severity: Critical, PR Type: Bugfix

#7460 Integration test fix
  .github/workflows/python-package.yml
  celery/app/task.py
  celery/canvas.py
  celery/contrib/pytest.py
  celery/worker/request.py
  requirements/test-integration.txt
  t/integration/tasks.py
  t/integration/test_canvas.py
  t/integration/test_tasks.py
Labels: CI

#7469 try pymongo[srv]>=4.0.2
  requirements/extras/mongodb.txt
Labels: Component: MongoDB Broker, Component: MongoDB Results Backend

#7470 Ensure task compression actually happens when setting `task_compression`
  celery/app/amqp.py
  t/unit/app/test_amqp.py
Labels: PR Type: Bugfix, Component: Task Serialization

#7472 Rabbitmq CI integration
  .github/workflows/python-package.yml
  t/integration/test_canvas.py
  t/integration/test_tasks.py
Labels: CI

#7356 Extend cassandra to cover AstraDB as well
  CONTRIBUTING.rst
  README.rst
  celery/app/defaults.py
  celery/backends/cassandra.py
  docs/includes/installation.txt
  docs/userguide/configuration.rst
  requirements/extras/cassandra.txt
  t/unit/backends/test_cassandra.py
Labels: Component: Cassandra Results Backend, PR Type: Enhancement, PR Type: Feature

#7477 update actions v3+
  .github/workflows/python-package.yml
Labels: CI

#7481 Missing `f` prefix on f-strings fix
  celery/backends/dynamodb.py
Labels: PR Type: Bugfix
