Repository celery/celery, pull requests merged in 2022-02, with the labels that each got.

#7232 Fix subscribed_to maybe empty
  celery/backends/redis.py
  t/unit/backends/test_redis.py
Labels: Status: Needs Test Coverage ✘, Component: Redis Results Backend, PR Type: Bugfix

#7297 fixed slight comment typo in celery/app/amqp.py
  celery/app/amqp.py
Labels: Category: Documentation

#7291 Fix: Celery beat sleeps 300 seconds sometimes even when it should run a task within a few seconds (e.g. 13 seconds) #7290
  celery/beat.py
  celery/utils/functional.py
  t/unit/app/test_beat.py
  t/unit/utils/test_functional.py
Labels: Component: Celerybeat, PR Type: Bugfix

#7292 Add `security_key_password` option
  CONTRIBUTORS.txt
  celery/app/base.py
  celery/app/defaults.py
  celery/security/__init__.py
  celery/security/key.py
  celery/security/serialization.py
  docs/userguide/configuration.rst
  docs/userguide/security.rst
  t/unit/app/test_app.py
  t/unit/security/__init__.py
  t/unit/security/test_key.py
  t/unit/security/test_security.py
  t/unit/security/test_serialization.py
Labels: PR Type: Enhancement, Component: Auth Serializer

#7307 Small documentation update: `task` -> `worker`
  docs/userguide/configuration.rst
Labels: PR Type: Bugfix, Category: Documentation
