Repository celery/celery, pull requests merged in 2022-06, with the labels that each got.

#7259 Crontab string representation does not match UNIX crontab expression
  celery/schedules.py
Labels: Component: Celerybeat, PR Type: Bugfix

#7544 Worker should exit with ctx.exit to get the right exitcode for non-zero cases
  celery/bin/worker.py
  requirements/test.txt
  t/integration/test_worker.py
  t/integration/test_worker_config.py
  t/unit/app/test_app.py
  t/unit/bin/proj/app.py
  t/unit/bin/test_worker.py
  t/unit/contrib/test_worker.py
  tox.ini
Labels: PR Type: Bugfix

#7268 Silence backend warning when eager results are stored
  celery/backends/base.py
Labels: PR Type: Enhancement

#7350 Reduce prefetch count on restart and gradually restore it
  celery/worker/consumer/consumer.py
  docs/userguide/workers.rst
  examples/app/myapp.py
  t/unit/worker/test_consumer.py
  t/unit/worker/test_worker.py
Labels: PR Type: Feature, Status: Has Test Coverage ✔, Component: Consumer, Status: Has Documentation✔

#7598 test kombu>=5.3.0a1,<6.0
  requirements/default.txt
Labels: CI

#7384 Canvas Header Stamping
  .github/workflows/python-package.yml
  celery/app/amqp.py
  celery/app/base.py
  celery/app/task.py
  celery/backends/base.py
  celery/canvas.py
  celery/utils/functional.py
  celery/worker/request.py
  docs/userguide/canvas.rst
  t/integration/conftest.py
  t/integration/tasks.py
  t/integration/test_canvas.py
  t/unit/conftest.py
  t/unit/tasks/test_canvas.py
  t/unit/tasks/test_chord.py
Labels: Component: Canvas, PR Type: Feature

#7597 async chords should pass it's kwargs to the group/body
  celery/canvas.py
  t/integration/test_canvas.py
  t/unit/tasks/test_chord.py
Labels: Component: Canvas, PR Type: Bugfix
