Repository celery/celery, pull requests merged in 2022-07, with the labels that each got.

#7608 beat: Suppress banner output with the quiet option
  celery/apps/beat.py
  celery/bin/beat.py
  t/unit/bin/proj/scheduler.py
  t/unit/bin/test_beat.py
Labels: PR Type: Bugfix, Component: CLI

#7626 Don't warn about DEBUG=True for Django
  celery/fixups/django.py
  t/unit/fixups/test_django.py
Labels: Component: Django, PR Type: Cleanup

#7652 Fixed the `on_after_finalize` cannot access `tasks` due to deadlock(Fixes #3589)
  celery/app/base.py
Labels: PR Type: Bugfix
