Repository celery/celery, pull requests merged in 2023-10, with the labels that each got.

#8519 Basic ElasticSearch / ElasticClient 8.x Support
  celery/backends/elasticsearch.py
  requirements/extras/elasticsearch.txt
  t/unit/backends/test_elasticsearch.py
Labels: Component: ElasticSearch Results Backend, PR Type: Enhancement

#8486 Fix eager tasks does not populate name field
  celery/app/task.py
  celery/result.py
  t/unit/tasks/test_result.py
  t/unit/tasks/test_tasks.py
Labels: Priority: Major, PR Type: Bugfix

#8241 Pytest Celery Integration
  .github/workflows/docker.yml
  .github/workflows/python-package.yml
  .gitignore
  requirements/extras/pytest.txt
  requirements/test-tmp_for_dev.txt
  requirements/test.txt
  t/integration/conftest.py
  t/integration/tasks.py
  t/smoke/__init__.py
  t/smoke/conftest.py
  t/smoke/signals.py
  t/smoke/tasks.py
  t/smoke/test_canvas.py
  t/smoke/test_consumer.py
  t/smoke/test_control.py
  t/smoke/test_failover.py
  t/smoke/test_signals.py
  t/smoke/workers/__init__.py
  t/smoke/workers/dev.py
  t/smoke/workers/docker/dev
  t/smoke/workers/docker/pypi
  t/smoke/workers/latest.py
  t/smoke/workers/legacy.py
  tox.ini
Labels: Category: Tests
