Repository celery/celery, pull requests merged in 2023-02, with the labels that each got.

#8044 Fixed formatting in setup.cfg that caused flake8 to misbehave
  celery/__init__.py
  celery/app/base.py
  celery/backends/base.py
  celery/bin/shell.py
  celery/concurrency/__init__.py
  celery/concurrency/asynpool.py
  celery/contrib/pytest.py
  celery/contrib/testing/app.py
  celery/contrib/testing/manager.py
  celery/contrib/testing/mocks.py
  celery/contrib/testing/worker.py
  celery/events/state.py
  celery/security/__init__.py
  celery/utils/collections.py
  celery/utils/log.py
  celery/utils/saferepr.py
  celery/utils/text.py
  celery/worker/consumer/consumer.py
  examples/celery_http_gateway/urls.py
  examples/django/proj/urls.py
  examples/stamping/myapp.py
  setup.cfg
  t/integration/test_canvas.py
  t/unit/app/test_beat.py
  t/unit/backends/test_database.py
  t/unit/bin/proj/app2.py
  t/unit/concurrency/test_eventlet.py
  t/unit/contrib/proj/foo.py
  t/unit/contrib/test_sphinx.py
  t/unit/contrib/test_worker.py
  t/unit/tasks/test_canvas.py
  t/unit/utils/test_functional.py
Labels: CI

#8046 Removed duplicated import Iterable
  t/unit/tasks/test_canvas.py
Labels: PR Type: Cleanup

#8047 Fix docs
  requirements/docs.txt
Labels: Category: Documentation, CI

#8045 Stamping Mechanism Refactoring
  celery/app/task.py
  celery/canvas.py
  t/integration/test_canvas.py
  t/unit/tasks/test_canvas.py
  t/unit/tasks/test_chord.py
  t/unit/tasks/test_stamping.py
Labels: Component: Canvas, PR Type: Bugfix, PR Type: Test Case

#8053 Fix cronjob that use day of month and negative UTC timezone
  celery/schedules.py
  celery/utils/time.py
  t/unit/app/test_schedules.py
Labels: Component: Celerybeat, PR Type: Bugfix

#8061 Fixed bug in Task.on_stamp_replaced()
  celery/app/task.py
  t/unit/tasks/test_stamping.py
Labels: PR Type: Bugfix

#8064 Stamping Mechanism Refactoring 2
  celery/app/task.py
  celery/canvas.py
  examples/stamping/examples.py
  examples/stamping/myapp.py
  examples/stamping/nested_replace_example.py
  examples/stamping/tasks.py
  examples/stamping/visitors.py
  t/unit/tasks/test_stamping.py
Labels: Component: Canvas

#8075 Improve documentation on ETA/countdown tasks (#8069)
  docs/faq.rst
  docs/getting-started/backends-and-brokers/redis.rst
  docs/userguide/calling.rst
Labels: Category: Documentation
