Repository celery/celery, pull requests merged in 2023-04, with the labels that each got.

#8201 Add Semgrep to CI
  .github/workflows/semgrep.yml
Labels: CI

#8202 Added semgrep to README.rst
  README.rst
Labels: Category: Documentation

#8197 Update django.txt
  requirements/extras/django.txt
Labels: Component: Django

#8206 start removing codecov from pypi
  requirements/test-ci-base.txt
Labels: CI

#8205 Update test.txt dependencies
  requirements/test.txt
Labels: CI

#8209 Improved doc for: worker_deduplicate_successful_tasks
  docs/userguide/configuration.rst
Labels: Category: Documentation

#8210 Renamed revoked_headers to revoked_stamps
  celery/worker/control.py
  celery/worker/request.py
  celery/worker/state.py
  t/integration/test_tasks.py
  t/unit/worker/test_control.py
  t/unit/worker/test_state.py
Labels: Component: Canvas
