Repository celery/celery, pull requests merged in 2023-09, with the labels that each got.

#8484 typo(doc): configuration.rst
  docs/userguide/configuration.rst
Labels: Category: Documentation

#8496 Update GHA checkout version
  .github/workflows/python-package.yml
Labels: CI

#8500 Fixed replaced_task_nesting
  celery/app/amqp.py
  celery/app/base.py
  t/integration/test_tasks.py
Labels: PR Type: Bugfix

#8508 Marked flaky tests
  t/integration/test_canvas.py
  t/integration/test_tasks.py
Labels: Category: Tests

#8501 Added support for replaced_task_nesting in chains
  celery/app/task.py
  t/integration/test_tasks.py
  t/unit/tasks/test_tasks.py
Labels: PR Type: Feature

#8509 Fix typos in canvas.rst
  docs/userguide/canvas.rst
Labels: Category: Documentation

#8488 Patch Version Release Checklist
  .github/ISSUE_TEMPLATE/Patch-Version-Release-Checklist.md
Labels: Category: Project Governance

#8511 Added Python 3.11 support to Dockerfile
  docker/Dockerfile
Labels: Component: Docker Image

#8530 Update test.txt
  requirements/test.txt
Labels: CI

#8531 Celery Docker Upgrades
  .github/workflows/docker.yml
  Makefile
  docker/Dockerfile
  t/integration/test_canvas.py
  tox.ini
Labels: Component: Docker Image, CI
