Repository celery/celery, pull requests merged in 2023-03, with the labels that each got.

#8092 Stamping documentation fixes & cleanups
  docs/userguide/canvas.rst
Labels: Component: Canvas, Category: Documentation

#8098 Deprecate parse_iso8601 in favor of fromisoformat
  celery/result.py
  celery/utils/iso8601.py
  celery/utils/time.py
  t/unit/tasks/test_tasks.py
Labels: PR Type: Cleanup

#8115 Fix potential AttributeError on 'stamps'
  celery/backends/base.py
  t/unit/backends/test_base.py
Labels: Component: Canvas, PR Type: Bugfix, Component: Result Backend

#8108 Type annotations for `celery/apps/beat.py`
  celery/apps/beat.py
  celery/schedules.py
  pyproject.toml
  t/unit/app/test_beat.py
Labels: Category: Documentation

#8120 Fixed bug where retrying a task loses its stamps
  celery/app/task.py
  t/integration/test_canvas.py
  t/unit/tasks/test_stamping.py
Labels: Component: Canvas, PR Type: Bugfix

#8134 fix: add expire string parse.
  celery/app/base.py
  t/unit/app/test_app.py
Labels: PR Type: Bugfix

#8133 Fix worker crash on un-pickleable exceptions
  celery/app/trace.py
  celery/exceptions.py
  celery/utils/serialization.py
  t/unit/tasks/test_tasks.py
Labels: PR Type: Bugfix, Component: Task Serialization

#8143 Warn when an unnamed periodic task override another one.
  celery/app/base.py
  docs/userguide/periodic-tasks.rst
  t/unit/app/test_app.py
Labels: Component: Celerybeat

#8156 Fix integration test
  t/integration/test_tasks.py
Labels: Issue Type: Regression

#8162 Fixed bug in revoke_by_stamped_headers where impl did not match doc
  celery/worker/control.py
  t/unit/worker/test_control.py
Labels: Component: Canvas, PR Type: Bugfix

#8163 Align revoke and revoke_by_stamped_headers return values (terminate=True)
  celery/worker/control.py
  t/unit/worker/test_control.py
Labels: Component: Canvas, PR Type: Bugfix
