Repository celery/celery, pull requests merged in 2024-03, with the labels that each got.

#8903 Fix recursive result parents on group in middle of chain
  celery/canvas.py
  t/integration/test_canvas.py
  t/unit/tasks/test_canvas.py
Labels: Component: Canvas, PR Type: Bugfix

#8899 Bump pytest-celery to 1.0.0b4
  requirements/extras/pytest.txt
  requirements/test.txt
  t/smoke/tests/test_consumer.py
  t/smoke/workers/docker/dev
  t/smoke/workers/docker/pypi
Labels: Category: Tests, CI

#8907 Adjusted smoke tests CI time limit
  .github/workflows/python-package.yml
Labels: Category: Tests, CI

#8918 Bump pytest-celery to 1.0.0rc1
  requirements/extras/pytest.txt
  requirements/test.txt
  t/smoke/workers/docker/dev
  t/smoke/workers/docker/pypi
Labels: dependencies

#8928 Bump pytest-celery to 1.0.0rc2
  requirements/extras/pytest.txt
  requirements/test.txt
  t/smoke/workers/docker/dev
  t/smoke/workers/docker/pypi
Labels: dependencies
