Repository celery/celery, pull requests merged in 2024-10, with the labels that each got.

#9333 Update user guide to recommend delay_on_commit
  docs/userguide/tasks.rst
Labels: Category: Documentation

#9341 Prepare for (pre) release: v5.5.0rc1
  .bumpversion.cfg
  Changelog.rst
  README.rst
  celery/__init__.py
  docs/history/changelog-5.5.rst
  docs/includes/introduction.txt
Labels: Category: Packaging and Release Management

#9350 Added Python 3.13 to Dockerfiles
  .github/workflows/docker.yml
  docker/Dockerfile
  t/smoke/workers/docker/dev
Labels: Component: Docker Image, CI

#9352 Skip test_pool_restart_import_modules on PyPy due to test issue
  t/unit/worker/test_control.py
Labels: Category: Tests

#9351 Add support for Google Pub/Sub transport
  README.rst
  celery/events/event.py
  celery/worker/consumer/mingle.py
  docs/getting-started/backends-and-brokers/gcpubsub.rst
  docs/getting-started/backends-and-brokers/index.rst
  docs/includes/installation.txt
Labels: PR Type: Feature

#9302 Add native incr support for GCSBackend
  celery/backends/gcs.py
  docs/userguide/configuration.rst
  requirements/extras/gcs.txt
  t/unit/backends/test_gcs.py
Labels: PR Type: Enhancement, Component: Google Cloud Storage Backend

#9374 Pass timeout and confirm_timeout to producer.publish()
  celery/app/amqp.py
  t/unit/app/test_amqp.py
Labels: Component: Kombu, PR Type: Bugfix

#9382 Bump Kombu to v5.5.0rc2
  requirements/default.txt
Labels: dependencies
