Repository celery/celery, pull requests merged in 2024-07, with the labels that each got.

#9117 Bump Kombu to v5.4.0rc1
  requirements/default.txt
Labels: dependencies

#9122 Increased smoke tests CI timeout
  .github/workflows/python-package.yml
Labels: Category: Tests

#9121 Added support for Quorum Queues
  celery/app/amqp.py
  celery/app/defaults.py
  celery/worker/consumer/tasks.py
  docs/userguide/configuration.rst
  examples/quorum-queues/declare_queue.py
  examples/quorum-queues/myapp.py
  examples/quorum-queues/setup_cluster.sh
  examples/quorum-queues/test_cluster.sh
  t/smoke/tests/quorum_queues/__init__.py
  t/smoke/tests/quorum_queues/conftest.py
  t/smoke/tests/quorum_queues/test_quorum_queues.py
  t/unit/app/test_amqp.py
  t/unit/worker/test_consumer.py
Labels: Component: RabbitMQ Broker, PR Type: Feature

#9139 Bump Kombu to v5.4.0rc3
  requirements/default.txt
Labels: dependencies

#9144 Added missing docs to previous releases
  docs/history/changelog-5.3.rst
  docs/history/changelog-5.4.rst
  docs/history/index.rst
Labels: Category: Documentation

#9145 Fixed a few documentation build warnings
  docs/history/changelog-5.3.rst
  docs/history/changelog-5.4.rst
  docs/history/whatsnew-5.3.rst
Labels: Category: Documentation

#9146 Prepare for (pre) release: v5.5.0b1
  .bumpversion.cfg
  Changelog.rst
  README.rst
  celery/__init__.py
  docs/django/first-steps-with-django.rst
  docs/history/changelog-5.5.rst
  docs/history/index.rst
  docs/history/whatsnew-5.5.rst
  docs/includes/introduction.txt
Labels: Category: Packaging and Release Management

#9159 Remove setuptools deprecated test command from setup.py
  setup.py
Labels: PR Type: Cleanup
