Repository celery/celery, pull requests merged in 2024-11, with the labels that each got.

#9395 Only log that global QoS is disabled if using amqp
  celery/worker/consumer/tasks.py
Labels: PR Type: Bugfix

#9408 Added a utility to format changelogs from the auto-generated GitHub release notes
  docs/Makefile
  docs/changelog_formatter.py
  requirements/pkgutils.txt
Labels: Category: Deployment

#9207 Native Delayed Delivery in RabbitMQ
  celery/app/base.py
  celery/app/defaults.py
  celery/backends/dynamodb.py
  celery/backends/elasticsearch.py
  celery/bin/base.py
  celery/utils/quorum_queues.py
  celery/worker/consumer/consumer.py
  celery/worker/consumer/delayed_delivery.py
  celery/worker/consumer/tasks.py
  docs/getting-started/backends-and-brokers/rabbitmq.rst
  docs/userguide/configuration.rst
  t/integration/tasks.py
  t/smoke/tests/quorum_queues/test_native_delayed_delivery.py
  t/unit/app/test_app.py
  t/unit/app/test_backends.py
  t/unit/tasks/test_tasks.py
  t/unit/worker/test_consumer.py
  t/unit/worker/test_native_delayed_delivery.py
Labels: Component: RabbitMQ Broker, PR Type: Feature

#9419 Document usage of broker_native_delayed_delivery_queue_type
  docs/getting-started/backends-and-brokers/rabbitmq.rst
Labels: PR Type: Enhancement, Category: Documentation

#9420 Adjust section in what's new document regarding quorum queues support
  docs/history/whatsnew-5.5.rst
Labels: PR Type: Enhancement, Category: Documentation

#9438 Added pypy to Dockerfile
  docker/Dockerfile
Labels: Component: Docker Image

#9439 Skipped flaky tests on pypy (all pass after ~10 reruns)
  t/unit/concurrency/test_prefork.py
Labels: Category: Tests
