Repository celery/celery, pull requests merged in 2024-06, with the labels that each got.

#9068 [enhance feature] Crontab schedule: allow using month names
  celery/schedules.py
  celery/utils/time.py
  t/unit/app/test_schedules.py
Labels: Component: Celerybeat, PR Type: Enhancement

#9073 Clarify docs about Reserve one task at a time
  docs/userguide/optimizing.rst
Labels: Category: Documentation

#9021 Bugfix - a task will run multiple times when chaining chains with groups
  celery/canvas.py
  t/integration/test_canvas.py
  t/smoke/tests/test_canvas.py
  t/unit/tasks/test_canvas.py
Labels: Component: Canvas
