Repository celery/celery, pull requests merged in 2025-03, with the labels that each got.

#9577 Improve docs about acks_on_failure_or_timeout
  celery/app/task.py
  docs/userguide/configuration.rst
  docs/userguide/tasks.rst
Labels: Category: Documentation

#9610 remove flake8plus as not needed anymore
  Makefile
  requirements/pkgutils.txt
Labels: PR Type: Cleanup

#9611 remove [bdist_wheel] universal = 0 from setup.cfg as not needed
  setup.cfg
Labels: Category: Packaging and Release Management, PR Type: Cleanup

#9624 Improve CI stability and performance
  .github/workflows/python-package.yml
  t/integration/test_tasks.py
Labels: CI

#9627 update tests to use python 3.8 codes only
  t/unit/tasks/test_canvas.py
Labels: Category: Tests, PR Type: Cleanup

#9626 #9597: Ensure surpassing Hard Timeout limit when task_acks_on_failure_or_timeout is False rejects the task
  celery/worker/request.py
  t/unit/worker/test_request.py
Labels: PR Type: Bugfix
