Repository celery/celery, pull requests merged in 2025-05, with the labels that each got.

#9683 Added DeepWiki to README
  README.rst
Labels: Category: Documentation

#9693 Limit redis to <=v5.2.1 to match Kombu
  requirements/extras/redis.txt
Labels: CI, dependencies

#9684 Use EX_OK instead of literal zero
  celery/worker/control.py
  t/unit/worker/test_control.py
Labels: PR Type: Enhancement

#9696 let celery install from kombu dependencies for better align
  requirements/extras/mongodb.txt
  requirements/extras/msgpack.txt
  requirements/extras/redis.txt
  requirements/extras/sqlalchemy.txt
  requirements/extras/sqs.txt
  requirements/extras/yaml.txt
Labels: Category: Packaging and Release Management

#9697 Fix stamping documentation to clarify stamped_headers key is optional in visitor methods
  docs/userguide/canvas.rst
Labels: Component: Canvas, Category: Documentation

#9716 ISSUE-9704: Update documentation of result_expires, filesystem backend is supported
  docs/userguide/configuration.rst
Labels: Category: Documentation
