Repository celery/celery, pull requests merged in 2025-08, with the labels that each got.

#9839 Bump Kombu to v5.6.0b1
  requirements/default.txt
Labels: dependencies

#9826 Fix Python 3.13 compatibility in events dumper
  celery/events/dumper.py
  t/unit/events/test_dumper.py
Labels: PR Type: Bugfix

#9733 Dockerfile Build Optimizations
  Makefile
  docker/Dockerfile
Labels: Component: Docker Image

#9824 Revert "Use Django DB max age connection setting"
  celery/fixups/django.py
  t/unit/fixups/test_django.py
Labels: Component: Django, PR Type: Enhancement, Issue Type: Regression

#9371 fix: prevent celery from hanging due to spawned greenlet errors in greenlet drainers
  .gitignore
  celery/backends/asynchronous.py
  celery/backends/redis.py
  t/unit/backends/test_asynchronous.py
Labels: Component: Gevent Workers Pool, PR Type: Bugfix
