Repository celery/celery, pull requests merged in 2025-02, with the labels that each got.

#9540 Update install-pyenv.sh
  docker/scripts/install-pyenv.sh
Labels: Component: Docker Image

#9549 Update Dockerfile by adding missing Python version 3.13
  docker/Dockerfile
Labels: Component: Docker Image

#9552 Fix the send_task method when detecting if the native delayed delivery approach is available
  celery/app/base.py
  t/unit/app/test_app.py
Labels: Component: RabbitMQ Broker, PR Type: Bugfix

#9494 Reverted PR #7814 & minor code improvement
  celery/app/log.py
  celery/apps/worker.py
  celery/platforms.py
  celery/utils/term.py
  t/unit/utils/test_platforms.py
  t/unit/utils/test_term.py
Labels: PR Type: Bugfix

#9558 Improved donation and sponsorship visibility
  README.rst
  docs/getting-started/backends-and-brokers/redis.rst
  docs/index.rst
Labels: Category: Documentation

#9559 Updated the Getting Help section, replacing deprecated with new resources
  docs/includes/resources.txt
  docs/index.rst
Labels: Category: Documentation

#9562 Fixed django example
  examples/django/proj/celery.py
  examples/django/proj/urls.py
Labels: Component: Django

#9564 Bump Kombu to v5.5.0rc3
  requirements/default.txt
Labels: dependencies

#9578 Canvas Stamping Doc Fixes
  celery/app/task.py
  docs/userguide/canvas.rst
  docs/userguide/workers.rst
Labels: Category: Documentation

#9580 Bugfix: Chord with a chord in header doesn't invoke error callback on inner chord header failure (default config)
  celery/canvas.py
  t/integration/test_canvas.py
  t/unit/tasks/test_canvas.py
  t/unit/tasks/test_stamping.py
Labels: PR Type: Bugfix
